---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-closing.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introducción a la recuperación ante desastres de BlueXP mediante Amazon EVS y Amazon FSxN. 
---
= Conclusión
:allow-uri-read: 


[role="lead"]
La recuperación ante desastres de BlueXP ofrece una solución de recuperación ante desastres en la nube híbrida y rentable para su infraestructura VMware local cuando se configura para usar Amazon EVS y Amazon FSx para NetApp ONTAP como destino de recuperación ante desastres. Esto le proporciona un destino de recuperación ante desastres robusto para infraestructuras de misión crítica. La recuperación ante desastres de BlueXP aprovecha las funciones nativas de protección de datos de ONTAP, respaldadas por décadas de experiencia en protección de datos, probadas exhaustivamente para garantizar la completa protección de sus datos.

Para más información:

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introducción a Amazon FSX para ONTAP de NetApp"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Documentación de recuperación ante desastres de NetApp BlueXP"]

