---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Una vez instalado el conector BlueXP, debe integrar todos los recursos de almacenamiento de ONTAP y VMware vCenter que participarán en el proceso de recuperación ante desastres. 
---
= Descripción general de la configuración de recuperación ante desastres de BlueXP para Amazon EVS
:allow-uri-read: 


[role="lead"]
Después de instalar BlueXP Connector, debe integrar todos los recursos de almacenamiento de ONTAP y VMware vCenter que participarán en el proceso de recuperación ante desastres con la recuperación ante desastres de BlueXP.

* link:evs-deploy-guide-config-prereqs.html["Requisitos previos para la recuperación ante desastres de Amazon EVS con BlueXP"]
* link:evs-deploy-guide-config-add-arrays.html["Agregue matrices de almacenamiento ONTAP a la recuperación ante desastres de BlueXP"]
* link:evs-deploy-guide-enable-draas.html["Habilitar la recuperación ante desastres de BlueXP para Amazon EVS"]
* link:evs-deploy-guide-config-add-arrays.html["Agregar sitios de vCenter a la recuperación ante desastres de BlueXP"]
* link:evs-deploy-guide-add-vcenters.html["Agregar clústeres de vCenter a la recuperación ante desastres de BlueXP"]

