---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: 'La cuenta de vCenter debe tener un conjunto mínimo de privilegios de vCenter para permitir que la recuperación ante desastres de BlueXP lleve a cabo sus servicios, como el registro y desregistro de almacenes de datos, iniciar y detener máquinas virtuales, y reconfigurar máquinas virtuales (VM). En la siguiente tabla se enumeran todos los privilegios necesarios para la recuperación ante desastres de BlueXP para interactuar con un clúster de vCenter.' 
---
= Se necesitan privilegios de vCenter para la recuperación ante desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
La cuenta de vCenter debe tener un conjunto mínimo de privilegios de vCenter para permitir que la recuperación ante desastres de BlueXP lleve a cabo sus servicios, como el registro y desregistro de almacenes de datos, iniciar y detener máquinas virtuales, y reconfigurar máquinas virtuales (VM). En la siguiente tabla se enumeran todos los privilegios necesarios para la recuperación ante desastres de BlueXP para interactuar con un clúster de vCenter.

[cols="25,35a,40a"]
|===
| Tipo | Nombre del privilegio | Descripción 


| *Datastore*  a| 
Almacén de datos. Configurar el almacén de datos
 a| 
Utilice para configurar un almacén de datos.



|   a| 
Almacén de datos. Quite el almacén de datos
 a| 
Utilice para quitar un almacén de datos.



| * Máquina virtual*  a| 
Máquina virtual.Configuración.Cambiar configuración
 a| 
Utilice para cambiar la configuración general de la máquina virtual.



|   a| 
Máquina virtual.Configuración.Modificar la configuración del dispositivo
 a| 
Se utiliza para cambiar las propiedades de un dispositivo existente.



|   a| 
Máquina virtual.Configuración.Volver a cargar desde la ruta de acceso
 a| 
Se utiliza para cambiar un parche de configuración de VM mientras se conserva la identidad de la VM. Soluciones como VMware vCenter Site Recovery Manager utilizan esta operación para mantener la identificación de máquinas virtuales durante la conmutación por error y la conmutación tras recuperación.



|   a| 
Virtual machine.Configuration.Renombrar
 a| 
Utilice para cambiar el nombre de una máquina virtual o modificar los nodos asociados de una máquina virtual.



|   a| 
Máquina virtual.Configuración.Restablecer información de invitado
 a| 
Se utiliza para editar la información del sistema operativo invitado para una máquina virtual.



|   a| 
Máquina virtual.Configuración.Cambiar memoria
 a| 
Utilice esta opción para cambiar la cantidad de memoria asignada a la máquina virtual.



|   a| 
Máquina virtual.Configuración.Cambiar el recuento de CPU
 a| 
Se utiliza para cambiar el número de CPU virtuales.



| *Virtual Machine Guest*  a| 
Máquina virtual. Operaciones de invitado. Modificaciones de la operación de invitado
 a| 
Permite operaciones invitadas de máquinas virtuales que involucran cambios en un sistema operativo invitado en una máquina virtual, como la transferencia de un archivo a la máquina virtual.



| * Interacción de la máquina virtual*  a| 
Máquina virtual.Interacción.Apagado
 a| 
Utilice para apagar una máquina virtual encendida. Esta operación apaga el sistema operativo invitado.



|   a| 
Máquina virtual.Interacción.Encendido
 a| 
Utilice el para encender una máquina virtual apagada y reanudar una máquina virtual suspendida.



|   a| 
Instalación de Virtual Machine.Interaction.VMware Tools
 a| 
Utilice para montar y desmontar el instalador del CD de VMware Tools como CD-ROM para el sistema operativo invitado.



| * Inventario de máquinas virtuales*  a| 
Máquina virtual.Inventory.Crear nuevo
 a| 
Se utiliza para crear una máquina virtual y asignar recursos para su ejecución.



|   a| 
Máquina virtual.Inventory.Register
 a| 
Utilice para añadir una máquina virtual existente a un inventario de host o una instancia de vCenter Server.



|   a| 
Máquina virtual.Inventory.Anular registro
 a| 
Utilice para cancelar el registro de una máquina virtual de un inventario de host o vCenter Server.



| *Estado de la máquina virtual*  a| 
Máquina virtual. Gestión de Snapshot.
 a| 
Se utiliza para crear una instantánea a partir del estado actual de la máquina virtual.



|   a| 
Máquina virtual. Gestión de Snapshot. Eliminar instantánea
 a| 
Se utiliza para eliminar una instantánea del historial de instantáneas.



|   a| 
Máquina virtual. Gestión de Snapshot. Revertir a snapshot
 a| 
Se utiliza para establecer el estado en el que estaba la máquina virtual en una snapshot determinada.

|===