---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: La revisión de los informes de recuperación ante desastres puede ayudarle a analizar su preparación para la recuperación ante desastres. Los informes prediseñados incluyen un resumen de las recuperaciones tras fallos y las recuperaciones tras fallos, detalles de replicación en todos los sitios y detalles de tareas del año pasado. 
---
= Crear informes de recuperación tras siniestros
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
La revisión de los informes de recuperación ante desastres puede ayudarle a analizar su preparación para la recuperación ante desastres. Los informes prediseñados incluyen un resumen de las recuperaciones tras fallos de prueba, detalles del plan de replicación y detalles de las tareas en todos los sitios de una cuenta durante los últimos siete días.

Es posible descargar los informes en formato PDF, HTML o JSON.

El enlace de descarga es válido durante seis horas.

.Pasos
. En el navegador izquierdo de BlueXP , selecciona *Protección* > *Recuperación de desastres* > *Planes de replicación*.
. En la parte superior de la página, selecciona *Crear informe*.
. Seleccione el tipo de formato de archivo y el período de tiempo de los últimos 7 días.
. Seleccione *Crear*.
+

NOTE: El informe puede tardar unos minutos en mostrarse.

. Para descargar un informe, seleccione *Descargar informe* y selecciónelo en la carpeta Descargar del administrador.

