---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites 
summary: Empieza a usar la recuperación de desastres de BlueXP verificando la compatibilidad de tu entorno, el acceso a la red, el inicio de sesión y el navegador web. 
---
= Requisitos previos de recuperación ante desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comience verificando la preparación de su entorno operativo, el inicio de sesión, el acceso a la red y el navegador web.

Para utilizar la recuperación ante desastres de BlueXP, debes asegurarte de que tu entorno cumpla los siguientes requisitos:

* Entorno de trabajo de VMware on-premises con almacenamiento de NetApp
* En AWS:
+
** Un sistema de archivos Amazon FSx para NetApp ONTAP. Consulte la documentación de Amazon FSx para ONTAP en https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["cómo comenzar"^].
** Una cuenta de VMware con un centro de datos definido por software (SDDC) en AWS, también conocido como Virtual Machines Cloud. En VMware Cloud Console, utilice las funciones de servicio de Administrator y NSX Cloud Administrator. Utilice también el propietario de la organización para el rol de organización. Consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Documentación de Virtual Machines Cloud"^].
** Enlace el centro de datos de desarrollo de software con Amazon FSx para NetApp ONTAP. Consulte https://vmc.techzone.vmware.com/fsx-guide#overview["Integración de VMware Cloud on AWS con Amazon FSx para NetApp ONTAP"^].


* En BlueXP:
+
** Credenciales de Amazon FSx para ONTAP y AWS agregadas al entorno de trabajo de BlueXP.
** Es necesario configurar el conector BlueXP en BlueXP. El conector local y en la nube deben tener conectividad tanto con el vCenter local como con VMware Cloud (VMC) con ESXis. Esto permite que las funciones de backup, conmutación al nodo de respaldo, conmutación por error y migración funcionen correctamente con las funciones de script y redes necesarias.
+
BlueXP Connector requiere credenciales tanto para los servidores de vCenter de origen como de destino. Consulte la https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["Inicio rápido de BlueXP"^] y.. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["Información de red de BlueXP"^].

** Para garantizar que los procesos de coherencia de la aplicación se realizan correctamente, asegúrese de cumplir los siguientes requisitos previos:
+
*** Asegúrese de que las herramientas de VMware (o Open VM Tools) se están ejecutando en las VM que estarán protegidas.
*** Para equipos virtuales Windows que ejecuten SQL, Oracle o ambos, las bases de datos deben tener activados sus instancias de VSS Writers y las bases de datos deben estar en estado estable.
*** Las bases de datos Oracle que se ejecutan en un sistema operativo Linux deben tener activada la autenticación de usuario del sistema operativo para el rol SYSDBA de la base de datos Oracle.





