---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites, bluexp disaster recovery 
summary: Antes de usar la recuperación ante desastres de BlueXP, debes asegurarte de que tu entorno cumpla los requisitos de almacenamiento de ONTAP, clúster de VMware vCenter y BlueXP. 
---
= Requisitos previos de recuperación ante desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Antes de usar la recuperación ante desastres de BlueXP, debes asegurarte de que tu entorno cumpla los requisitos de almacenamiento de ONTAP, clúster de VMware vCenter y BlueXP.



== Requisitos previos de almacenamiento ONTAP

Estos requisitos previos se aplican a instancias de ONTAP o Amazon FSx para NetApp ONTAP.

* Los clústeres de origen y destino deben tener una relación entre iguales.
* La SVM que alojará los volúmenes de recuperación ante desastres debe existir en el clúster de destino.
* La SVM de origen y la SVM de destino deben tener una relación entre iguales.
+

NOTE: No se deben crear volúmenes de recuperación ante desastres en la SVM o las SVM de destino. La recuperación ante desastres de BlueXP creará los volúmenes de destino según sea necesario para el plan de replicación.

* Si se realiza la puesta en marcha con Amazon FSx para NetApp ONTAP, se aplican los siguientes requisitos previos:
+
** Debe haber una instancia de Amazon FSx para NetApp ONTAP para alojar almacenes de datos de recuperación de desastres de VMware en el VPC. Consulte la documentación de Amazon FSx para ONTAP en https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["cómo comenzar"^].






== Requisitos previos de los clústeres de VMware vCenter

Estos requisitos previos se aplican tanto a clústeres de vCenter en las instalaciones como al centro de datos definido por software (SDDC) de VMware Cloud para AWS.

* Todos los clústeres de VMware que quieras que gestione la recuperación ante desastres de BlueXP se deben alojar en ONTAP Volumes.
* Todos los almacenes de datos de VMware que se gestionen mediante la recuperación ante desastres de BlueXP deben usar uno de los siguientes protocolos:
+
** NFS
** VMFS con el protocolo iSCSI o FC


* VMware vSphere versión 7,0 Update 3 (7.0v3) o posterior
* Si utiliza VMware Cloud SDDC, se aplican estos requisitos previos.
+
** En VMware Cloud Console, utilice las funciones de servicio de Administrator y NSX Cloud Administrator. Utilice también el propietario de la organización para el rol de organización. Consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Usar VMware Cloud Foundations con documentación de AWS FSx para NetApp ONTAP"^].
** Vincula el centro de datos definido por software de VMware Cloud con Amazon FSx para la instancia de NetApp ONTAP. Consulte https://vmc.techzone.vmware.com/fsx-guide#overview["Integración de VMware Cloud on AWS con la información sobre la puesta en marcha de Amazon FSx para NetApp ONTAP"^].






== Requisitos previos de BlueXP



=== Comience con BlueXP

Si aún no lo ha hecho, https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["Regístrese en BlueXP  y cree una organización"^]



=== Recopile las credenciales para ONTAP y VMware

* Las credenciales de Amazon FSx para ONTAP y AWS se deben agregar al entorno de trabajo dentro del proyecto BlueXP  que se utilizarán para gestionar la recuperación ante desastres de BlueXP .
* La recuperación ante desastres de BlueXP requiere credenciales de vCenter. Introduce las credenciales de vCenter cuando añade un sitio en la recuperación ante desastres de BlueXP.
+
Para ver una lista de los privilegios de vCenter necesarios, consulte link:../reference/vcenter-privileges.html["Se necesitan privilegios de vCenter para la recuperación ante desastres de BlueXP"]. Para obtener instrucciones sobre cómo agregar un sitio, consulte link:../use/sites-add.html["Agregar un sitio"].





=== Crea un conector BlueXP

Debe configurarse un conector BlueXP en BlueXP. Cuando uses BlueXP Connector, incluirá las funcionalidades adecuadas para el servicio de recuperación ante desastres.

* La recuperación ante desastres de BlueXP solo funciona con la puesta en marcha de Connector en modo estándar. Consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["Introducción a BlueXP en modo estándar"^].
* Asegúrese de que tanto el vCenter de origen como el de destino utilicen el mismo conector BlueXP.
* Tipo de conector BlueXP necesario:
+
** *Recuperación ante desastres local a local*: Instale el conector local de BlueXP en el sitio de recuperación ante desastres. Consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Instalar y configurar un conector en las instalaciones"^].
** *En las instalaciones a AWS*: Instala el conector BlueXP para AWS en tu VPC de AWS. Consulte https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["Opciones de instalación de conectores en AWS"^].
+

TIP: Para entornos locales a locales, utiliza el conector on-premises de BlueXP. Para las instalaciones a AWS, utiliza BlueXP AWS Connector, que tiene acceso al vCenter de origen en las instalaciones y al vCenter en las instalaciones de destino.

** El conector BlueXP instalado debe poder acceder a cualquier clúster de VMware que gestione la recuperación ante desastres de BlueXP.


* Todas las cabinas de ONTAP que se gestionarán mediante la recuperación ante desastres de BlueXP  deben añadirse a cualquier entorno de trabajo dentro del proyecto de BlueXP  que se utilizará para gestionar la recuperación ante desastres de BlueXP .
+
Consulte https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Detectar clústeres de ONTAP en las instalaciones"^].

* Para obtener más información sobre la configuración de un proxy inteligente para la recuperación ante desastres de BlueXP , consulte link:../get-started/dr-setup.html["Configura tu infraestructura para la recuperación ante desastres de BlueXP"].




== Requisitos previos de carga de trabajo

Para garantizar que los procesos de coherencia de la aplicación se realicen correctamente, aplique estos requisitos previos:

* Asegúrese de que las herramientas de VMware (o Open VM Tools) se están ejecutando en las VM que estarán protegidas.
* Para equipos virtuales Windows que ejecuten Microsoft SQL Server, Oracle Database o ambos, las bases de datos deben tener activados sus Escritores de VSS.
* Las bases de datos Oracle que se ejecutan en un sistema operativo Linux deben tener activada la autenticación de usuario del sistema operativo para el rol SYSDBA de la base de datos Oracle.

