---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, 
summary: Para utilizar la recuperación ante desastres de BlueXP, realiza unos pasos para configurarla. 
---
= Configura la recuperación de desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para utilizar la recuperación ante desastres de BlueXP, lleva a cabo unos pasos para configurarlo tanto en AWS como en BlueXP.


TIP: Revisar link:../get-started/dr-prerequisites.html["requisitos previos"] garantizar que su entorno está listo.



== Configure en AWS

En AWS, tendrás que seguir los siguientes pasos:

* Pon en marcha y configura VMware Cloud en AWS.
* Crea un sistema de archivos de Amazon FSx para ONTAP. Aprovisiona y configura FSx para ONTAP.
* Utilizar una cuenta de VMware y aprovisionar el centro de datos definido mediante software (SDDC). Asegúrate de que el SDDC tiene conectividad con FSx para ONTAP.




=== Ponga en marcha VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud en AWS"^] Proporciona una experiencia nativa del cloud para cargas de trabajo basadas en VMware en el ecosistema de AWS. Cada centro de datos definido por software (SDDC) de VMware se ejecuta en un cloud privado virtual (VPC) de Amazon y proporciona una pila completa de VMware (incluida vCenter Server), redes definidas por software NSX-T, almacenamiento definido por software vSAN y uno o varios hosts ESXi que proporcionan recursos de computación y almacenamiento para las cargas de trabajo.

Para configurar un entorno VMC en AWS, siga estos pasos https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["enlace"^]. También se puede usar un clúster piloto para la recuperación ante desastres.



=== Configura Amazon FSx para NetApp ONTAP

Amazon FSX para ONTAP de NetApp es un servicio totalmente gestionado que ofrece un almacenamiento de archivos altamente fiable, escalable, de alto rendimiento y con numerosas funciones incorporado en el popular sistema de archivos ONTAP de NetApp. Siga estos pasos https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["enlace"^] Para aprovisionar y configurar FSx para NetApp ONTAP.



== Configurar en BlueXP

El siguiente paso es configurar la recuperación de desastres en BlueXP.

* Crear un conector en BlueXP.
* Pon en marcha y configura SnapMirror para Amazon FSx para NetApp ONTAP.
* Añade el entorno de trabajo del almacenamiento de ONTAP on-premises a BlueXP. Este es el clúster de ONTAP de origen.
* Añade una cuenta de BlueXP, añade FSxN al entorno de trabajo y añade credenciales de AWS para FSx for ONTAP.




=== Crear un conector en BlueXP

Tienes que registrarte para acceder a la vista previa o ponerte en contacto con tu representante de ventas de NetApp para probar este servicio. A continuación, cuando utilices BlueXP Connector, incluirá las funcionalidades adecuadas para el servicio de recuperación ante desastres.

Para crear un conector en BlueXP antes de utilizar el servicio, consulte la documentación de BlueXP que se describe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["cómo crear un conector"^].

Usa el conector on-premises de BlueXP o el conector BlueXP AWS, que tiene acceso al vCenter de origen on-premises y al vCenter on-premises de destino.



=== Configurar SnapMirror para Amazon FSx para NetApp ONTAP

El siguiente paso es configurar la recuperación de desastres en BlueXP.

. En BlueXP, añade una cuenta. Consulte la https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html["Documentación de BlueXP sobre cómo añadir una cuenta"^].
. Agregue Amazon FSx para NetApp ONTAP al entorno de trabajo. Comprobar que la relación de SnapMirror con el clúster de ONTAP está instalada y que dispone de un destino de FSx para NetApp ONTAP. Consulte https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Cómo configurar un entorno de trabajo FSx para ONTAP"^].
. En BlueXP, pon en marcha SnapMirror en FSx para NetApp ONTAP.
. En BlueXP, detecta el FSx aprovisionado para NetApp ONTAP en una instancia de AWS y replica los volúmenes de almacén de datos especificados desde un entorno on-premises a FSx para NetApp ONTAP con la frecuencia adecuada y la retención de las copias de Snapshot de NetApp.




=== Configurar la licencia

Con la recuperación ante desastres de BlueXP, puedes registrarte para disfrutar de una prueba gratuita de 90 días.
