---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Para utilizar la recuperación ante desastres de BlueXP, realiza unos pasos para configurarla. 
---
= Configura tu infraestructura para la recuperación ante desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para utilizar la recuperación ante desastres de BlueXP, lleve a cabo unos pasos para configurarlo tanto en Amazon Web Services (AWS) como en BlueXP.


TIP: Revisar link:../get-started/dr-prerequisites.html["requisitos previos"] garantizar que su entorno está listo.



== Prepárate para la recuperación ante desastres de BlueXP

* Verifique su entorno de producción.
+
** Asegúrese de que las máquinas virtuales que desee proteger están alojadas en almacenes de datos NFS (con volúmenes de NFS de ONTAP) o en almacenes de datos VMFS (con LUN iSCSI de NetApp).
** Asegúrese de tener credenciales y claves de acceso para sus cabinas ONTAP, vCenters e instancias de cloud VMware alojadas en AWS.


* Cree o verifique su sitio de recuperación ante desastres.
+
** Cree o verifique que su sistema de archivos de Amazon FSx está listo.
** Asegúrate de que las máquinas virtuales de origen y destino tienen una relación entre iguales.






== Configure VMware Cloud para AWS SDDC

Configurar el centro de datos definido por software (SDDC) de VMware Cloud para AWS

* Crea un sistema de archivos de Amazon FSx para ONTAP. Aprovisiona y configura FSx para ONTAP. Amazon FSX para ONTAP de NetApp es un servicio totalmente gestionado que ofrece un almacenamiento de archivos altamente fiable, escalable, de alto rendimiento y con numerosas funciones incorporado en el popular sistema de archivos ONTAP de NetApp.
* Sigue los pasos que puedes seguir https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["enlace"^] https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Inicio rápido de Amazon FSX para ONTAP de NetApp"] para aprovisionar y configurar FSx para NetApp ONTAP.
* Añade Amazon FSx para NetApp ONTAP al entorno de trabajo y añade las credenciales de AWS para FSx para ONTAP.
* En AWS, tendrás que seguir los siguientes pasos:
+
** Pon en marcha y configura VMware Cloud en AWS.
** Utilice una cuenta de VMware y aprovisione el SDDC. Asegúrate de que el SDDC tiene conectividad con FSx para ONTAP.






=== Ponga en marcha VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud en AWS"^] Proporciona una experiencia nativa del cloud para cargas de trabajo basadas en VMware en el ecosistema de AWS. Cada centro de datos definido por software (SDDC) de VMware se ejecuta en un cloud privado virtual (VPC) de Amazon y proporciona una pila completa de VMware (incluida vCenter Server), redes definidas por software NSX-T, almacenamiento definido por software vSAN y uno o varios hosts ESXi que proporcionan recursos de computación y almacenamiento para las cargas de trabajo.

Para configurar un entorno VMC en AWS, siga estos pasos https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["enlace"^]. También se puede usar un clúster piloto para la recuperación ante desastres.



== Configurar la licencia

Con la recuperación ante desastres de BlueXP, puedes registrarte para disfrutar de una prueba gratuita de 90 días.

Puede adquirir uno de los siguientes:

* Una suscripción de pago por uso (PAYGO) con AWS Marketplace
* BYOL (BYOL), que es un Archivo de licencia de NetApp (NLF).


Consulte link:../get-started/dr-licensing.html["Configurar las licencias de recuperación de desastres de BlueXP"].
