---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Para utilizar la recuperación ante desastres de BlueXP, realiza unos pasos para configurarla. 
---
= Configura tu infraestructura para la recuperación ante desastres de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para utilizar la recuperación ante desastres de BlueXP, lleve a cabo unos pasos para configurarlo tanto en Amazon Web Services (AWS) como en BlueXP.


TIP: Revisar link:../get-started/dr-prerequisites.html["requisitos previos"] garantizar que su entorno está listo.



== Prepárate para la recuperación de desastres de BlueXP  para una protección on-premises a la on-premises

Asegúrese de que se cumplen los siguientes requisitos antes de configurar la recuperación de desastres de BlueXP  para la protección de las instalaciones a las instalaciones:

* Almacenamiento de ONTAP
+
** Asegúrese de que tiene credenciales de ONTAP.
** Cree o verifique su sitio de recuperación ante desastres.
** Cree o verifique su SVM de ONTAP de destino.
** Asegúrese de que las SVM de ONTAP de origen y de destino tienen una relación entre iguales.


* Clústeres de vCenter
+
** Asegúrese de que las máquinas virtuales que desea proteger estén alojadas en almacenes de datos NFS (con volúmenes de NFS de ONTAP) o en almacenes de datos VMFS (con LUN iSCSI de NetApp).
** Se requiere revisión link:../reference/vcenter-privileges.html["Privileges de vCenter"]para la recuperación ante desastres de BlueXP .
** Cree una cuenta de usuario de recuperación ante desastres (no la cuenta de administrador de vCenter predeterminada) y asigne la instancia de vCenter Privileges a la cuenta.






=== Compatibilidad con proxy inteligente

El conector BlueXP  admite proxy inteligente. El proxy inteligente es una forma ligera, segura y eficiente de conectar tu entorno on-premises al servicio BlueXP . Proporciona una conexión segura entre su entorno y el servicio BlueXP  sin requerir una VPN ni acceso directo a Internet. Esta implementación de proxy optimizada libera el tráfico de API dentro de la red local.

Cuando se configura un proxy, la recuperación ante desastres de BlueXP  intenta comunicarse directamente con VMware o ONTAP y utiliza el proxy configurado si falla la comunicación directa.

La implementación del proxy de recuperación ante desastres de BlueXP  requiere comunicación del puerto 443 entre el conector y todas las instancias de vCenter Server y las cabinas ONTAP mediante un protocolo HTTPS. El agente de recuperación ante desastres de BlueXP  dentro de Connector se comunica directamente con VMware vSphere, el VC o ONTAP cuando realiza cualquier acción.

Para obtener más información sobre la configuración general de proxy en BlueXP , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configure un conector para que utilice un servidor proxy"^].



== Prepárate para la recuperación de desastres de BlueXP  para conseguir una protección on-premises a la nube con AWS

Para configurar la recuperación de desastres de BlueXP  para la protección de las instalaciones al cloud mediante AWS, tienes que configurar lo siguiente:

* Configura AWS FSx para NetApp ONTAP
* Configurar VMware Cloud en AWS SDDC




=== Configura AWS FSx para NetApp ONTAP

* Crea un sistema de archivos de Amazon FSx para NetApp ONTAP.
+
** Aprovisiona y configura FSx para ONTAP. Amazon FSx para NetApp ONTAP es un servicio totalmente gestionado que ofrece un almacenamiento de archivos con una gran cantidad de funciones, altamente fiable, escalable y de alto rendimiento basado en el sistema de archivos NetApp ONTAP.
** Siga los pasos indicados en https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Informe técnico 4938: Monta Amazon FSx ONTAP como almacén de datos NFS con VMware Cloud on AWS"^] y https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Inicio rápido de Amazon FSX para ONTAP de NetApp"] para aprovisionar y configurar FSx para ONTAP.


* Añade Amazon FSx para ONTAP al entorno de trabajo y añade las credenciales de AWS para FSx para ONTAP.
* Cree o verifique su SVM de ONTAP de destino en la instancia de AWS FSx para ONTAP.
* Configura la replicación entre tu clúster de ONTAP de origen en las instalaciones y tu instancia de FSx para ONTAP en BlueXP .


Consulte https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Cómo configurar un entorno de trabajo FSx para ONTAP"^] para obtener más información.



=== Configurar VMware Cloud en AWS SDDC

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud en AWS"^] Proporciona una experiencia nativa del cloud para cargas de trabajo basadas en VMware en el ecosistema de AWS. Cada centro de datos definido por software (SDDC) de VMware se ejecuta en un cloud privado virtual (VPC) de Amazon y proporciona una pila completa de VMware (incluida vCenter Server), redes definidas por software NSX-T, almacenamiento definido por software vSAN y uno o varios hosts ESXi que proporcionan recursos de computación y almacenamiento para las cargas de trabajo.

Para configurar un entorno de VMware Cloud en AWS, siga los pasos de https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Implemente y configure el entorno de virtualización en AWS"^]. También se puede utilizar un clúster piloto para la recuperación de desastres.
