---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: La recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. Con la recuperación ante desastres de BlueXP para VMware, puedes replicar tus cargas de trabajo de VMware on-premises que ejecutan el almacenamiento ONTAP en un centro de datos definido por software de VMware en nubes públicas como sitio de recuperación ante desastres mediante el almacenamiento en la nube de NetApp. 
---
= Novedades en la recuperación ante desastres de BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubre las novedades de la recuperación ante desastres de BlueXP.



== 13 de mayo de 2025

Versión 4.2.3



=== Asignación de subred

Con esta versión, puede gestionar las direcciones IP en caso de conmutación por error de una forma nueva mediante la asignación de subred, lo que permite añadir subredes para cada vCenter. Al hacerlo, debe definir el CIDR IPv4, la puerta de enlace predeterminada y el DNS para cada red virtual.

Tras la conmutación por error, la recuperación ante desastres de BlueXP  determina la dirección IP adecuada de cada VNIC observando el CIDR proporcionado para la red virtual asignada y lo utiliza para derivar la nueva dirección IP.

Por ejemplo:

* NetworkA = 10,1.1.0/24
* NetworkB = 192.168.1.0/24


VM1 tiene una VNIC (10,1.1,50) que está conectada a NetworkA. NetworkA se asigna a NetworkB en la configuración del plan de replicación.

Tras la conmutación por error, la recuperación ante desastres de BlueXP  sustituye la parte de red de la dirección IP original (10,1.1) y mantiene la dirección de host (.50) de la dirección IP original (10,1.1,50). Para VM1, la recuperación ante desastres de BlueXP  examina la configuración CIDR para NetworkB y utiliza la parte de red 192.168.1 de NetworkB mientras mantiene la parte de host (.50) para crear la nueva dirección IP para VM1. La nueva dirección IP se convierte en 192.168.1.50.

En resumen, la dirección de host permanece igual, mientras que la dirección de red se sustituye por lo que esté configurado en la asignación de subred del sitio. Esto le permite gestionar la reasignación de direcciones IP en caso de fallo con mayor facilidad, especialmente si tiene cientos de redes y miles de máquinas virtuales que gestionar.

Para obtener más información sobre cómo incluir la asignación de subred en los sitios, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Añada sitios de vCenter Server"] .



=== Omitir la protección

Ahora puede omitir la protección para que el servicio no cree automáticamente una relación de protección inversa después de una conmutación al respaldo del plan de replicación. Esto resulta útil si desea realizar operaciones adicionales en el sitio restaurado antes de volver a conectarlo en línea dentro de la recuperación ante desastres de BlueXP .

Cuando inicia una conmutación al respaldo, de forma predeterminada el servicio crea automáticamente una relación de protección inversa para cada volumen del plan de replicación, si el sitio de origen original está en línea. Esto significa que el servicio crea una relación de SnapMirror desde el sitio de destino de vuelta al sitio de origen. El servicio también revierte automáticamente la relación de SnapMirror cuando inicia una conmutación de retorno tras recuperación.

Al iniciar una conmutación por error, ahora puede elegir una opción de *Omitir protección*. Con esto, el servicio no invierte automáticamente la relación de SnapMirror. En su lugar, deja el volumen editable en ambos lados del plan de replicación.

Después de que el sitio de origen original vuelva a estar en línea, puede establecer la protección inversa seleccionando *Proteger recursos* en el menú Acciones del plan de replicación. Esto intenta crear una relación de replicación inversa para cada volumen del plan. Puede ejecutar este trabajo varias veces hasta que se restaure la protección. Una vez restaurada la protección, puede iniciar una conmutación de retorno tras recuperación de la forma habitual.

Para obtener más información sobre la protección contra omisiones, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Fallo de las aplicaciones ovre en un sitio remoto"] .



=== SnapMirror programa actualizaciones en el plan de replicación

La recuperación ante desastres de BlueXP  ahora admite el uso de soluciones de gestión de snapshots externas, como el planificador de políticas nativo de ONTAP SnapMirror o las integraciones de terceros con ONTAP. Si todos los almacenes de datos (volúmenes) del plan de replicación ya tienen una relación de SnapMirror que se gestiona en otros lugares, puede usar esos snapshots como puntos de recuperación en la recuperación ante desastres de BlueXP .

Para configurarlo, en la sección Plan de replicación > Asignación de recursos, marque la casilla de verificación *Usar copias de seguridad administradas por plataforma y programas de retención* al configurar la asignación de almacenes de datos.

Cuando se selecciona, la recuperación ante desastres de BlueXP  no configura una programación de backup. Sin embargo, todavía debe configurar un programa de retención porque es posible que aún se realicen instantáneas para operaciones de prueba, conmutación por error y conmutación de retorno tras recuperación.

Una vez configurado, el servicio no toma ninguna instantánea programada regularmente, sino que depende de la entidad externa para tomar y actualizar esas instantáneas.

Para obtener más información sobre la protección contra omisiones, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"] .



== 16 de abril de 2025

Versión 4.2.2



=== Detección programada para máquinas virtuales

La recuperación ante desastres de BlueXP  realiza la detección una vez cada 24 horas. Con esta versión, ahora puede personalizar el programa de detección para satisfacer sus necesidades y reducir el impacto en el rendimiento cuando lo necesite. Por ejemplo, si tiene una gran cantidad de máquinas virtuales, puede configurar la programación de detección para que se ejecute cada 48 horas. Si tiene una cantidad pequeña de máquinas virtuales, puede configurar la programación de detección para que se ejecute cada 12 horas.

Si no wan programa la detección, puede deshabilitar la opción de detección programada y actualizar la detección manualmente en cualquier momento.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Añada sitios de vCenter Server"] .



=== Compatibilidad con almacenes de datos de grupo de recursos

Antes, solo podía crear grupos de recursos por máquinas virtuales. Con esta versión, es posible crear un grupo de recursos por almacenes de datos. Cuando crea un plan de replicación y crea un grupo de recursos para ese plan, se mostrarán todas las máquinas virtuales de un almacén de datos. Esta característica resulta útil si tiene una gran cantidad de máquinas virtuales y desea agruparlas por almacén de datos.

Es posible crear un grupo de recursos con un almacén de datos de las siguientes maneras:

* Cuando se añade un grupo de recursos mediante almacenes de datos, se muestra una lista de almacenes de datos. Puede seleccionar uno o varios almacenes de datos para crear un grupo de recursos.
* Cuando crea un plan de replicación y crea un grupo de recursos dentro del plan, puede ver las máquinas virtuales en los almacenes de datos.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Notificaciones de prueba gratuita o vencimiento de licencia

Esta versión proporciona notificaciones de que la prueba gratuita caducará en 60 días para garantizar que tenga tiempo para obtener una licencia. Esta versión también proporciona notificaciones el día en que caduca la licencia.



=== Notificación de actualizaciones de servicio

Con esta versión, aparece un banner en la parte superior para indicar que los servicios se están actualizando y que el servicio se coloca en modo de mantenimiento. El banner aparece cuando el servicio se está actualizando y desaparece cuando se completa la actualización. Aunque puede seguir trabajando en la interfaz de usuario mientras la actualización está en curso, no puede enviar nuevos trabajos. Los trabajos programados se ejecutarán una vez finalizada la actualización y el servicio volverá al modo de producción.



== 10 de marzo de 2025

Versión 4.2.1



=== Compatibilidad con proxy inteligente

El conector BlueXP  admite proxy inteligente. El proxy inteligente es una forma ligera, segura y eficiente de conectar tu entorno on-premises al servicio BlueXP . Proporciona una conexión segura entre su entorno y el servicio BlueXP  sin requerir una VPN ni acceso directo a Internet. Esta implementación de proxy optimizada libera el tráfico de API dentro de la red local.

Cuando se configura un proxy, la recuperación ante desastres de BlueXP  intenta comunicarse directamente con VMware o ONTAP y utiliza el proxy configurado si falla la comunicación directa.

La implementación del proxy de recuperación ante desastres de BlueXP  requiere comunicación del puerto 443 entre el conector y todas las instancias de vCenter Server y las cabinas ONTAP mediante un protocolo HTTPS. El agente de recuperación ante desastres de BlueXP  dentro de Connector se comunica directamente con VMware vSphere, el VC o ONTAP cuando realiza cualquier acción.

Para obtener más información sobre el proxy inteligente para la recuperación de desastres de BlueXP , consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Configura tu infraestructura para la recuperación ante desastres de BlueXP"].

Para obtener más información sobre la configuración general de proxy en BlueXP , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Configure un conector para que utilice un servidor proxy"^].



=== Finalice la prueba gratuita en cualquier momento

Puede detener la prueba gratuita en cualquier diente o puede esperar hasta que caduque.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Finalice la prueba gratuita"].



== 19 de febrero de 2025

Versión 4,2



=== Compatibilidad de ASA R2 para máquinas virtuales y almacenes de datos en almacenamiento VMFS

Esta versión de la recuperación ante desastres de BlueXP  ofrece compatibilidad con ASA R2 para máquinas virtuales y almacenes de datos en almacenamiento VMFS. En un sistema ASA R2, el software ONTAP admite la funcionalidad SAN básica, mientras que quita funciones que no son compatibles con los entornos SAN.

Esta versión admite las siguientes funciones de ASA R2:

* Aprovisionamiento de grupos de consistencia para el almacenamiento primario (únicamente grupo de coherencia plano, es decir, sólo un nivel sin una estructura jerárquica)
* Operaciones de backup (grupo de consistencia) incluida la automatización de SnapMirror


La compatibilidad con ASA R2 en la recuperación ante desastres de BlueXP  utiliza ONTAP 9.16.1.

Si bien los almacenes de datos se pueden montar en un volumen ONTAP o en una unidad de almacenamiento de ASA R2, un grupo de recursos de la recuperación ante desastres de BlueXP  no puede incluir tanto un almacén de datos de ONTAP como uno de ASA R2. Es posible seleccionar un almacén de datos de ONTAP o un almacén de datos de ASA R2 en un grupo de recursos.



== 30 de octubre de 2024



=== Creación de informes

Ahora puede generar y descargar informes para ayudarle a analizar su paisaje. Los informes prediseñados resumen las recuperaciones tras fallos y las recuperaciones tras fallos, muestran los detalles de la replicación en todos los sitios y muestran los detalles del trabajo de los últimos siete días.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Crear informes de recuperación tras siniestros"].



=== prueba gratuita de 30 días

Ahora puedes registrarte para disfrutar de una prueba gratuita de 30 días de recuperación ante desastres de BlueXP . Anteriormente, las pruebas gratuitas eran de 90 días.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurar la licencia"].



=== Desactive y active los planes de replicación

Una versión anterior incluía actualizaciones de la estructura del programa de prueba de conmutación por error, que era necesaria para soportar los programas diarios y semanales. Esta actualización requería deshabilitar y volver a activar todos los planes de replicación existentes para poder utilizar los nuevos programas de prueba de conmutación por error diarios y semanales. Este es un requisito único.

Le contamos cómo:

. En el menú superior, selecciona *Planes de replicación*.
. Seleccione un plan y seleccione el icono Acciones para mostrar el menú desplegable.
. Seleccione *Desactivar*.
. Después de unos minutos, selecciona *Habilitar*.




=== Asignación de carpetas

Al crear un plan de replicación y asignar recursos de computación, ahora puede asignar carpetas de modo que se recuperen las máquinas virtuales en una carpeta que especifique para el centro de datos, el clúster y el host.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Los detalles de la máquina virtual están disponibles para la conmutación al nodo de respaldo, la conmutación de retorno tras recuperación y la conmutación

Cuando se produce un fallo y se inicia una conmutación al respaldo, una conmutación de retorno tras recuperación o una prueba de la conmutación por error, ahora puede ver los detalles de los equipos virtuales e identificar qué equipos virtuales no se reiniciaron.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Conmute al nodo de respaldo de las aplicaciones en un sitio remoto"].



=== Retraso en el arranque de equipos virtuales con una secuencia de arranque ordenada

Al crear un plan de replicación, ahora puede establecer un retraso de inicio para cada VM del plan. De este modo, es posible establecer una secuencia para que las máquinas virtuales se inicien para garantizar que se ejecute toda la prioridad que se tienen unas máquinas virtuales antes de que se inicien las siguientes de prioridad.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Información del sistema operativo del equipo virtual

Al crear un plan de replicación, ahora puede ver el sistema operativo de cada VM del plan. Esto es útil para decidir cómo agrupar máquinas virtuales en un grupo de recursos.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Alias de nombres de VM

Al crear un plan de replicación, ahora puede agregar un prefijo y un sufijo a los nombres de los equipos virtuales en el área de recuperación ante desastres. Esto permite usar un nombre más descriptivo para las máquinas virtuales del plan.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Limpie las instantáneas antiguas

Es posible eliminar las copias de Snapshot que ya no se necesiten más allá del recuento de retención especificado. Las copias Snapshot pueden acumularse con el tiempo al reducir el número de retención de snapshots y ahora puede quitarlas para liberar espacio. Puede hacerlo en cualquier momento bajo demanda o cuando elimine un plan de replicación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Administre la información de sitios, grupos de recursos, planes de replicación, almacenes de datos y máquinas virtuales"] .



=== Conciliar instantáneas

Ahora puede conciliar instantáneas que no estén sincronizadas entre el origen y el destino. Esto puede suceder si se eliminan las copias Snapshot en un destino fuera de la recuperación tras desastres de BlueXP . El servicio elimina la snapshot de origen automáticamente cada 24 horas. Sin embargo, puede realizar esto bajo demanda. Esta función le permite asegurarse de que las instantáneas sean coherentes en todos los sitios.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar planes de replicación"] .



== 20 de septiembre de 2024



=== Compatibilidad con almacenes de datos VMFS de VMware desde las instalaciones hasta en las instalaciones

Esta versión incluye compatibilidad con máquinas virtuales montadas en almacenes de datos del sistema de archivos de máquina virtual (VMFS) de VMware vSphere para iSCSI y FC protegidos en almacenamiento en las instalaciones. Anteriormente, el servicio ofrecía una _technology preview_ que admitía los almacenes de datos VMFS para iSCSI y FC.

A continuación se muestran algunas consideraciones adicionales relativas a los protocolos iSCSI y FC:

* La compatibilidad con FC es para los protocolos de interfaz de cliente, no para la replicación.
* La recuperación ante desastres de BlueXP  solo admite una única LUN por volumen ONTAP. El volumen no debe tener varios LUN.
* Para cualquier plan de replicación, el volumen ONTAP de destino debe utilizar los mismos protocolos que el volumen ONTAP de origen que aloja las máquinas virtuales protegidas. Por ejemplo, si el origen utiliza un protocolo FC, el destino debe utilizar también FC.




== 2 de agosto de 2024



=== Compatibilidad con almacenes de datos VMFS de VMware para FC tanto en las instalaciones como en las instalaciones

Esta versión incluye una vista previa _tecnológica_ de soporte para máquinas virtuales montadas en almacenes de datos del sistema de archivos para máquinas virtuales (VMFS) de VMware vSphere para FC protegido al almacenamiento en las instalaciones. Anteriormente, el servicio ofrecía una vista previa de la tecnología que admitía almacenes de datos VMFS para iSCSI.


NOTE: NetApp no le cobra por ninguna capacidad de carga de trabajo vista previa.



=== Cancelación de trabajo

Con esta versión, ahora puede cancelar un trabajo en la interfaz de usuario de Job Monitor.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Supervisar trabajos"].



== 17 de julio de 2024



=== Programas de prueba de conmutación por error

Esta versión incluye actualizaciones de la estructura del programa de prueba de conmutación por error, que era necesaria para soportar los programas diarios y semanales. Esta actualización requiere que desactive y vuelva a activar todos los planes de replicación existentes para poder utilizar los nuevos programas de prueba de conmutación por error diarios y semanales. Este es un requisito único.

Le contamos cómo:

. En el menú superior, selecciona *Planes de replicación*.
. Seleccione un plan y seleccione el icono Acciones para mostrar el menú desplegable.
. Seleccione *Desactivar*.
. Después de unos minutos, selecciona *Habilitar*.




=== Actualizaciones del plan de replicación

Esta versión incluye actualizaciones de los datos del plan de replicación, lo que resuelve un problema de «instantánea no encontrada». Esto requiere cambiar el recuento de retención en todos los planes de replicación a 1 e iniciar una instantánea bajo demanda. Este proceso crea una nueva copia de seguridad y elimina todas las copias de seguridad más antiguas.

Le contamos cómo:

. En el menú superior, selecciona *Planes de replicación*.
. Seleccione el plan de replicación, haga clic en la pestaña *Asignación de conmutación por error* y haga clic en el icono del lápiz *Editar*.
. Haga clic en la flecha *datastores* para expandirla.
. Observe el valor del recuento de retención en el plan de replicación. Tendrá que restablecer este valor original cuando haya terminado con estos pasos.
. Reduzca el conteo a 1.
. Inicie una snapshot bajo demanda. Para hacerlo, en la página del plan de replicación, seleccione el plan, haga clic en el icono Acciones y seleccione *Tomar instantánea ahora*.
. Una vez que el trabajo de instantánea se haya completado correctamente, aumente el recuento del plan de replicación hasta el valor original que anotó en el primer paso.
. Repita estos pasos para todos los planes de replicación existentes.




== 5 de julio de 2024

Esta versión de recuperación de desastres de BlueXP incluye las siguientes actualizaciones:



=== Compatibilidad con AFF A-Series

En esta versión se admiten las plataformas de hardware NetApp AFF A-series.



=== Compatibilidad con almacenes de datos VMFS de VMware desde las instalaciones hasta en las instalaciones

Esta versión incluye una vista previa _tecnológica_ de soporte para máquinas virtuales montadas en almacenes de datos del sistema de archivos de máquina virtual (VMFS) de VMware vSphere protegidos en almacenamiento en las instalaciones. Con este lanzamiento, la recuperación de desastres se admite en una vista previa tecnológica de las cargas de trabajo de VMware en las instalaciones al entorno VMware en las instalaciones con almacenes de datos VMFS.


NOTE: NetApp no le cobra por ninguna capacidad de carga de trabajo vista previa.



=== Actualizaciones del plan de replicación

Puede agregar un plan de replicación más fácilmente filtrando las máquinas virtuales por almacén de datos en la página Aplicaciones y seleccionando más detalles de destino en la página Asignación de recursos. Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Editar planes de replicación

Con esta versión, la página de asignaciones de failover se ha mejorado para una mayor claridad.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar planes"].



=== Editar las máquinas virtuales

Con esta versión, el proceso de edición de máquinas virtuales en el plan incluyó algunas mejoras menores en la interfaz de usuario.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar máquinas virtuales"].



=== Actualizaciones de conmutación al respaldo

Antes de iniciar una conmutación por error, ahora puede determinar el estado de las máquinas virtuales y si están encendidas o apagadas. Ahora el proceso de conmutación por error le permite tomar una copia Snapshot ahora o elegir las instantáneas.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Conmute al nodo de respaldo de las aplicaciones en un sitio remoto"].



=== Programas de prueba de conmutación por error

Ahora puede editar las pruebas de conmutación por error y establecer programas diarios, semanales y mensuales para la prueba de conmutación por error.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar planes"].



=== Actualizaciones de la información de requisitos previos

Se actualizó la información de requisitos previos de recuperación de desastres de BlueXP .

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Requisitos previos de recuperación ante desastres de BlueXP"].



== 15 de mayo de 2024

Esta versión de recuperación de desastres de BlueXP incluye las siguientes actualizaciones:



=== Replicar las cargas de trabajo de VMware de on-premises a on-premises

Ahora se publica como una característica de disponibilidad general. Anteriormente, era una vista previa de la tecnología con funcionalidad limitada.



=== Actualizaciones de licencias

Con la recuperación ante desastres de BlueXP , puedes registrarte para disfrutar de una prueba gratuita de 90 días, comprar una suscripción de pago por uso (PAYGO) con Amazon Marketplace o BYOL (BYOL), que es un archivo de licencia de NetApp (NLF) que obtienes al representante de ventas de NetApp o al sitio de soporte de NetApp (NSS).

Para obtener más detalles sobre cómo configurar la licencia para la recuperación ante desastres de BlueXP, consulte link:../get-started/dr-licensing.html["Configurar la licencia"].

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].



== 5 de marzo de 2024

Esta es la versión de Disponibilidad general de la recuperación de desastres de BlueXP, que incluye las siguientes actualizaciones.



=== Actualizaciones de licencias

Con la recuperación ante desastres de BlueXP , puedes registrarte para disfrutar de una prueba gratuita de 90 días o BYOL (Bring Your Own License), que es un archivo de licencia de NetApp (NLF) que obtienes de tu representante de ventas de NetApp Puede utilizar el número de serie de la licencia para activar la licencia de licencia en la cartera digital de BlueXP. Los cargos de recuperación ante desastres de BlueXP se basan en la capacidad aprovisionada de los almacenes de datos.

Para obtener más detalles sobre cómo configurar la licencia para la recuperación ante desastres de BlueXP, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurar la licencia"].

Para obtener más información sobre la gestión de licencias para los servicios de *All* BlueXP, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Gestiona las licencias para todos los servicios de BlueXP"^].



=== Editar programaciones

Con esta versión, ahora puede configurar programas para probar pruebas de cumplimiento y de conmutación por error, de modo que se asegure de que funcionarán correctamente en caso de necesitarlas.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree el plan de replicación"].



== 1 de febrero de 2024

Esta versión previa de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones:



=== Mejora de la red

Con esta versión, ahora puede cambiar el tamaño de los valores de CPU y RAM de VM. Ahora también puede seleccionar una dirección IP estática o DHCP de red para la máquina virtual.

* DHCP: Si elige esta opción, proporcionará credenciales para la máquina virtual.
* Static IP: Puede seleccionar la misma información o una diferente de la máquina virtual de origen. Si elige lo mismo que el origen, no necesita introducir credenciales. Por otro lado, si elige utilizar información diferente de la fuente, puede proporcionar las credenciales, la dirección IP, la máscara de subred, el DNS y la información de la puerta de enlace.


Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Scripts personalizados

Ahora se puede incluir como procesos posteriores a la conmutación al respaldo. Con scripts personalizados, puedes ejecutar tu script de recuperación ante desastres de BlueXP después de un proceso de conmutación al respaldo. Por ejemplo, puede utilizar un script personalizado para reanudar todas las transacciones de la base de datos una vez finalizada la operación de failover.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Conmutación al nodo de respaldo en un sitio remoto"].



=== Relación de SnapMirror

Ahora puede crear una relación de SnapMirror mientras desarrolla el plan de replicación. Anteriormente, tenías que crear la relación fuera de la recuperación ante desastres de BlueXP.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Grupos de consistencia

Cuando se crea un plan de replicación, puede incluir máquinas virtuales de diferentes volúmenes y diferentes SVM. La recuperación ante desastres de BlueXP crea una snapshot de grupo de consistencia incluyendo todos los volúmenes y actualizaciones todas las ubicaciones secundarias.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Opción de retraso de encendido de la máquina virtual

Al crear un plan de replicación, puede añadir máquinas virtuales a un grupo de recursos. Con los grupos de recursos, puede establecer un retraso en cada máquina virtual para que se inicien una secuencia retrasada.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Copias Snapshot consistentes con las aplicaciones

Puede especificar para crear copias de Snapshot consistentes con las aplicaciones. El servicio desactivará la aplicación y, a continuación, realizará una snapshot para obtener un estado coherente de la aplicación.

Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



== 11 de enero de 2024

Esta versión preliminar de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones:



=== Crear el panel con mayor rapidez

Con esta versión, puede acceder a la información de otras páginas desde el Dashboard más rápidamente.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].



== 20 de octubre de 2023

Esta versión preliminar de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones.



=== Proteja las cargas de trabajo de VMware basadas en NFS en las instalaciones

Ahora, con la recuperación ante desastres de BlueXP, puedes proteger tus cargas de trabajo de VMware basadas en NFS on-premises frente a desastres en otro entorno de VMware basado en NFS en las instalaciones además del cloud público. La recuperación de desastres de BlueXP orquesta la finalización de los planes de recuperación ante desastres.


NOTE: Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].



== 27 de septiembre de 2023

Esta versión preliminar de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones:



=== Actualizaciones de la consola

Ahora puede hacer clic en las opciones del Panel de Control, lo que le facilitará revisar la información rápidamente. Además, la consola ahora muestra el estado de conmutaciones al respaldo y migraciones.

Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Vea el estado de sus planes de recuperación ante desastres en la Consola"].



=== Actualizaciones del plan de replicación

* *RPO*: Ahora puede ingresar el objetivo de punto de recuperación (RPO) y el recuento de retención en la sección datastores del plan de replicación. Indica la cantidad de datos que debe existir que no es anterior a la hora establecida. Si, por ejemplo, lo configura en 5 minutos, el sistema puede perder hasta 5 minutos de datos si hay un desastre sin que ello afecte a las necesidades vitales para el negocio.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].

* *Mejoras de red*: Cuando mapeas la red entre las ubicaciones de origen y destino en la sección de máquinas virtuales del plan de replicación, la recuperación ante desastres de BlueXP ahora ofrece dos opciones: DHCP o IP estática. Anteriormente, solo DHCP era compatible. Para las IP estáticas, debe configurar la subred, la puerta de enlace y los servidores DNS. Además, ahora puede introducir credenciales para máquinas virtuales.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].

* *Editar horarios*: Ahora puede actualizar los horarios del plan de replicación.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar recursos"].

* *Automatización de SnapMirror*: Mientras crea el plan de replicación en esta versión, puede definir la relación de SnapMirror entre los volúmenes de origen y de destino en una de las siguientes configuraciones:
+
** 1 a 1
** 1 a muchos en una arquitectura fanout
** Muchos a 1 como un grupo de consistencia
** Muchos A VARIOS
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].







== 1 de agosto de 2023



=== Vista previa de la recuperación ante desastres de BlueXP 

La vista previa de la recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. Inicialmente, con la vista previa de la recuperación ante desastres de BlueXP, puedes proteger las cargas de trabajo de VMware basadas en NFS que ejecutan el almacenamiento NetApp en VMware Cloud (VMC) en AWS con Amazon FSx for ONTAP.


NOTE: Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].

Esta versión incluye las siguientes actualizaciones:



=== Los grupos de recursos se actualizan para el orden de inicio

Al crear un plan de recuperación ante desastres o replicación, puede agregar máquinas virtuales a grupos de recursos funcionales. Los grupos de recursos permiten poner un conjunto de máquinas virtuales dependientes en grupos lógicos que cumplan sus requisitos. Por ejemplo, los grupos pueden contener un orden de inicio que se puede ejecutar tras la recuperación. Con esta versión, cada grupo de recursos puede incluir una o más máquinas virtuales. Las máquinas virtuales se encenderán según la secuencia en la que las incluya en el plan. Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Seleccione aplicaciones para replicar y asignar grupos de recursos"].



=== Verificación de replicación

Después de crear el plan de recuperación ante desastres o replicación, identificar la repetición del asistente e iniciar una replicación a un sitio de recuperación ante desastres, cada 30 minutos de recuperación ante desastres de BlueXP  verifica que la replicación se produzca según el plan. Puede supervisar el progreso en la página Job Monitor. Consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Replicar aplicaciones en otro sitio"].



=== El plan de replicación muestra los programas de transferencia de objetivo de punto de recuperación (RPO)

Al crear un plan de recuperación ante desastres o replicación, selecciona las máquinas virtuales. En esta versión, ahora puede ver el SnapMirror asociado con cada uno de los volúmenes que estén asociados con el almacén de datos o la máquina virtual. También se pueden ver las programaciones de transferencia de RPO asociadas con la programación de SnapMirror. El RPO ayuda a determinar si la programación de backup es suficiente para recuperarse después de un desastre. Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].



=== Actualización de Job Monitor

La página Job Monitor ahora incluye una opción Refresh para que pueda obtener un estado actualizado de las operaciones. Consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Supervisar los trabajos de recuperación ante desastres"].



== 18 de mayo de 2023

Esta es el lanzamiento inicial de la recuperación ante desastres de BlueXP.



=== Servicio de recuperación ante desastres basado en cloud

La recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. Inicialmente, con la vista previa de la recuperación ante desastres de BlueXP, puedes proteger las cargas de trabajo de VMware basadas en NFS que ejecutan el almacenamiento NetApp en VMware Cloud (VMC) en AWS con Amazon FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].
