---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery faq, bluexp, disaster recovery frequently asked questions, vmware, vcenter 
summary: La recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. 
---
= Lo nuevo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubre las novedades de la previsualización de la recuperación de desastres de BlueXP.



== 20 de octubre de 2023

Esta versión preliminar de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones.

Ahora, con la recuperación ante desastres de BlueXP, puedes proteger tus cargas de trabajo de VMware basadas en NFS on-premises frente a desastres en otro entorno de VMware basado en NFS en las instalaciones además del cloud público. La recuperación de desastres de BlueXP orquesta la finalización de los planes de recuperación ante desastres.


NOTE: Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].



== 27 de septiembre de 2023

Esta versión preliminar de la recuperación ante desastres de BlueXP incluye las siguientes actualizaciones:

* *Actualizaciones del tablero*: Ahora puede hacer clic en las opciones del tablero, lo que le facilita revisar la información rápidamente. Además, la consola ahora muestra el estado de conmutaciones al respaldo y migraciones.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Vea el estado de sus planes de recuperación ante desastres en la Consola"].

* *Actualizaciones del plan de replicación*:
+
** *RPO*: Ahora puede ingresar el objetivo de punto de recuperación (RPO) y el recuento de retención en la sección datastores del plan de replicación. Indica la cantidad de datos que debe existir que no es anterior a la hora establecida. Si, por ejemplo, lo configura en 5 minutos, el sistema puede perder hasta 5 minutos de datos si hay un desastre sin que ello afecte a las necesidades vitales para el negocio.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].

** *Mejoras de red*: Cuando mapeas la red entre las ubicaciones de origen y destino en la sección de máquinas virtuales del plan de replicación, la recuperación ante desastres de BlueXP ahora ofrece dos opciones: DHCP o IP estática. Anteriormente, solo DHCP era compatible. Para las IP estáticas, debe configurar la subred, la puerta de enlace y los servidores DNS. Además, ahora puede introducir credenciales para máquinas virtuales.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].

** *Editar horarios*: Ahora puede actualizar los horarios del plan de replicación.
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Gestionar recursos"].

** *Automatización de SnapMirror*: Mientras crea el plan de replicación en esta versión, puede definir la relación de SnapMirror entre los volúmenes de origen y de destino en una de las siguientes configuraciones:
+
*** 1 a 1
*** 1 a muchos en una arquitectura fanout
*** Muchos a 1 como un grupo de consistencia
*** Muchos A VARIOS
+
Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].









== 1 de agosto de 2023

La vista previa de la recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. Inicialmente, con la vista previa de la recuperación ante desastres de BlueXP, puedes proteger las cargas de trabajo de VMware basadas en NFS que ejecutan el almacenamiento NetApp en VMware Cloud (VMC) en AWS con Amazon FSx for ONTAP.


NOTE: Con esta oferta de vista previa, NetApp se reserva el derecho de modificar los detalles, el contenido y la línea de tiempo de la oferta antes de la disponibilidad general.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].

Esta versión incluye las siguientes actualizaciones:

* *Actualización de grupos de recursos para orden de arranque*: Cuando crea un plan de recuperación ante desastres o replicación, puede agregar máquinas virtuales a grupos de recursos funcionales. Los grupos de recursos permiten poner un conjunto de máquinas virtuales dependientes en grupos lógicos que cumplan sus requisitos. Por ejemplo, los grupos pueden contener un orden de inicio que se puede ejecutar tras la recuperación. Con esta versión, cada grupo de recursos puede incluir una o más máquinas virtuales. Las máquinas virtuales se encenderán según la secuencia en la que las incluya en el plan. Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Seleccione aplicaciones para replicar y asignar grupos de recursos"].
* *Verificación de replicación*: Después de crear el plan de recuperación ante desastres o replicación, identificar la recurrencia en el asistente e iniciar una replicación en un sitio de recuperación ante desastres, cada 30 minutos de recuperación ante desastres de BlueXP verifica que la replicación se produzca realmente de acuerdo con el plan. Puede supervisar el progreso en la página Job Monitor. Consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Replicar aplicaciones en otro sitio"].
* *El plan de replicación muestra los horarios de transferencia del objetivo de punto de recuperación (RPO)*: Cuando creas un plan de recuperación ante desastres o replicación, seleccionas las VM. En esta versión, ahora puede ver el SnapMirror asociado con cada uno de los volúmenes que estén asociados con el almacén de datos o la máquina virtual. También se pueden ver las programaciones de transferencia de RPO asociadas con la programación de SnapMirror. El RPO ayuda a determinar si la programación de backup es suficiente para recuperarse después de un desastre. Consulte https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Cree un plan de replicación"].
* *Actualización de Job Monitor*: La página Job Monitor ahora incluye una opción Refresh para que pueda obtener un estado actualizado de las operaciones. Consulte  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Supervisar los trabajos de recuperación ante desastres"].




== 18 de mayo de 2023

Esta es el lanzamiento inicial de la recuperación ante desastres de BlueXP.

La recuperación de desastres de BlueXP es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres. Inicialmente, con la vista previa de la recuperación ante desastres de BlueXP, puedes proteger las cargas de trabajo de VMware basadas en NFS que ejecutan el almacenamiento NetApp en VMware Cloud (VMC) en AWS con Amazon FSx for ONTAP.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Obtén más información sobre la recuperación ante desastres de BlueXP"].
